// <auto-generated />
using Hris.Database;
using Hris.Database.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Hris.Database.Migrations
{
    [DbContext(typeof(HrisContext))]
    [Migration("20180510035115_DbInitial")]
    partial class DbInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hris.Database.Entities.Action", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Event")
                        .HasMaxLength(50);

                    b.Property<string>("Key")
                        .HasMaxLength(50);

                    b.Property<int?>("LanguageId");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Order");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Hris.Database.Entities.ActionLanguage", b =>
                {
                    b.Property<int?>("ActionId");

                    b.Property<int?>("LanguageId");

                    b.Property<string>("Name");

                    b.HasKey("ActionId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("ActionLanguages");
                });

            modelBuilder.Entity("Hris.Database.Entities.FormLanguage", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("FunctionId");

                    b.Property<string>("FunctionKey")
                        .HasMaxLength(50);

                    b.Property<string>("Key")
                        .HasMaxLength(50);

                    b.Property<int?>("LanguageId");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("Value")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("LanguageId");

                    b.ToTable("FormLanguages");
                });

            modelBuilder.Entity("Hris.Database.Entities.Function", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Icon")
                        .HasMaxLength(50);

                    b.Property<string>("Key")
                        .HasMaxLength(50);

                    b.Property<int>("Module");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("OrderIndex");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("Hris.Database.Entities.FunctionAction", b =>
                {
                    b.Property<int?>("ActionId");

                    b.Property<int?>("FunctionId");

                    b.HasKey("ActionId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("FunctionActions");
                });

            modelBuilder.Entity("Hris.Database.Entities.FunctionLanguage", b =>
                {
                    b.Property<int?>("FunctionId");

                    b.Property<int?>("LanguageId");

                    b.Property<string>("Name");

                    b.HasKey("FunctionId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("FunctionLanguages");
                });

            modelBuilder.Entity("Hris.Database.Entities.Language", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Hris.Database.Entities.Role", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Hris.Database.Entities.RoleFunction", b =>
                {
                    b.Property<int?>("FunctionId");

                    b.Property<int?>("RoleId");

                    b.HasKey("FunctionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleFunctions");
                });

            modelBuilder.Entity("Hris.Database.Entities.RoleFunctionAction", b =>
                {
                    b.Property<int?>("RoleId");

                    b.Property<int?>("ActionId");

                    b.Property<int?>("FunctionId");

                    b.HasKey("RoleId", "ActionId", "FunctionId");

                    b.HasIndex("ActionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("RoleFunctionActions");
                });

            modelBuilder.Entity("Hris.Database.Entities.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("DateFormat")
                        .HasMaxLength(20);

                    b.Property<string>("DecimalSymbol")
                        .HasMaxLength(1);

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("DigitGroupingSymbol")
                        .HasMaxLength(1);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Fullname")
                        .HasMaxLength(50);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50);

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10);

                    b.Property<int?>("LanguageId");

                    b.Property<DateTime?>("LastLogin");

                    b.Property<string>("Password")
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<string>("TimeFormat")
                        .HasMaxLength(10);

                    b.Property<int?>("TimeZone");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("Username")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hris.Database.Entities.UserRole", b =>
                {
                    b.Property<int?>("RoleId");

                    b.Property<int?>("UserId");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Hris.Database.Entities.Action", b =>
                {
                    b.HasOne("Hris.Database.Entities.Language")
                        .WithMany("Actions")
                        .HasForeignKey("LanguageId");
                });

            modelBuilder.Entity("Hris.Database.Entities.ActionLanguage", b =>
                {
                    b.HasOne("Hris.Database.Entities.Action", "Action")
                        .WithMany("ActionLanguages")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hris.Database.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hris.Database.Entities.FormLanguage", b =>
                {
                    b.HasOne("Hris.Database.Entities.Function", "Function")
                        .WithMany("FormLanguages")
                        .HasForeignKey("FunctionId");

                    b.HasOne("Hris.Database.Entities.Language", "Language")
                        .WithMany("FormLanguages")
                        .HasForeignKey("LanguageId");
                });

            modelBuilder.Entity("Hris.Database.Entities.FunctionAction", b =>
                {
                    b.HasOne("Hris.Database.Entities.Action", "Action")
                        .WithMany("FunctionActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hris.Database.Entities.Function", "Function")
                        .WithMany("FunctionActions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hris.Database.Entities.FunctionLanguage", b =>
                {
                    b.HasOne("Hris.Database.Entities.Function", "Function")
                        .WithMany("FunctionLanguages")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hris.Database.Entities.Language", "Language")
                        .WithMany("FunctionLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hris.Database.Entities.RoleFunction", b =>
                {
                    b.HasOne("Hris.Database.Entities.Function", "Function")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hris.Database.Entities.Role", "Role")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hris.Database.Entities.RoleFunctionAction", b =>
                {
                    b.HasOne("Hris.Database.Entities.Action", "Action")
                        .WithMany("RoleFunctionActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hris.Database.Entities.Function", "Function")
                        .WithMany("RoleFunctionActions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hris.Database.Entities.Role", "Role")
                        .WithMany("RoleFunctionActions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hris.Database.Entities.User", b =>
                {
                    b.HasOne("Hris.Database.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");
                });

            modelBuilder.Entity("Hris.Database.Entities.UserRole", b =>
                {
                    b.HasOne("Hris.Database.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hris.Database.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
